"""info_routine and exercise

Revision ID: 47df32aa53e5
Revises: 1228614c3c16
Create Date: 2026-07-03 15:47:17.754112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47df32aa53e5'
down_revision = '1228614c3c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('sets', sa.String(length=200), nullable=True),
    sa.Column('reps', sa.String(length=255), nullable=True),
    sa.Column('example_link', sa.String(length=255), nullable=True),
    sa.Column('weights', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('info_routines',
    sa.Column('day', sa.String(length=40), nullable=True),
    sa.Column('name_section', sa.String(length=80), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_routines')
    op.drop_table('exercises')
    # ### end Alembic commands ###
