"""elimina tabla user_routine

Revision ID: 9a551f5053ad
Revises: 98f06e080929
Create Date: 2026-07-14 16:29:36.022711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a551f5053ad'
down_revision = '98f06e080929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_routines')
    with op.batch_alter_table('info_routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sets', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('reps', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('weights', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_routines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('weights')
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')
        batch_op.drop_column('comment')
        batch_op.drop_column('description')

    op.create_table('user_routines',
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name=op.f('user_routines_routine_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_routines_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_routines_pkey'))
    )
    # ### end Alembic commands ###
