"""correcciones

Revision ID: a76f0f64adb4
Revises: 47df32aa53e5
Create Date: 2026-07-06 15:04:39.973337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76f0f64adb4'
down_revision = '47df32aa53e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.String(length=200), nullable=True))
        batch_op.drop_column('adrees')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adrees', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('adress')

    # ### end Alembic commands ###
