"""info_users

Revision ID: e40c84dbd41f
Revises: 7b09a03ec893
Create Date: 2026-07-03 14:14:14.370722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40c84dbd41f'
down_revision = '7b09a03ec893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_users',
    sa.Column('dni', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('number_phone', sa.String(length=50), nullable=True),
    sa.Column('adrees', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'info_users', ['info_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('info_user_id')

    op.drop_table('info_users')
    # ### end Alembic commands ###
